const colors = {
  light: {
    text: "#111827",
    tint: "#7C3AED",
    background: "#F9FAFB",
    foreground: "#111827",
    card: "#FFFFFF",
    cardForeground: "#111827",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    secondary: "#F3F4F6",
    secondaryForeground: "#374151",
    muted: "#F3F4F6",
    mutedForeground: "#6B7280",
    accent: "#EDE9FE",
    accentForeground: "#4C1D95",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E5E7EB",
    input: "#E5E7EB",
  },
  dark: {
    text: "#F9FAFB",
    tint: "#A78BFA",
    background: "#0D0D0F",
    foreground: "#F9FAFB",
    card: "#18181B",
    cardForeground: "#F9FAFB",
    primary: "#8B5CF6",
    primaryForeground: "#FFFFFF",
    secondary: "#1F1F24",
    secondaryForeground: "#D1D5DB",
    muted: "#1F1F24",
    mutedForeground: "#9CA3AF",
    accent: "#2D2438",
    accentForeground: "#C4B5FD",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#27272A",
    input: "#27272A",
  },
  radius: 12,
};

export default colors;
